### ISSUE TITLE
Better scrolling

### ISSUE THREAD

**Issue by lokesh-krishna** [wbrawner/SimpleMarkdown#10]
Presently, scrolling through a document in Edit view is very tedious. Scrolling only occurs as long as the user's finger is actually scrolling on the screen, making it impossible to flick which is very handy when it comes to long documents. Also missing is a scroll bar.

The Preview view has got both of these and it would be really nice if the Edit view too supported these features.

**Comment by wbrawner** [comment]
Thanks, I'll look into this :)

**Comment by wbrawner** [comment]
This'll be going out in the next beta release :)

**Comment by wbrawner** [comment]
Closing since #25 was merged :)
