### ISSUE TITLE
Keyboard Hotkeys Not Supported

### ISSUE THREAD

**Issue by PeterHindes** [wbrawner/SimpleMarkdown#100]
It doesn't save when pressing CTRL-S or open file with CTRL-O etc. It would be nice for keyboard users to have this functionality.

**Comment by wbrawner** [comment]
This sounds like a reasonable feature to me

**Comment by wbrawner** [comment]
I've added them in 4b144e80cc9f401191448fad3bbeb5e99a268116, so keep an eye out for them in the next release
