### ISSUE TITLE
Typing with Bluetooth keyboard while auto save is on makes some characters get reverted.

### ISSUE THREAD

**Issue by PeterHindes** [wbrawner/SimpleMarkdown#101]
Basically what the title says, if I don't turn off auto save when typing with a physical keyboard it deletes some letters as I type and I have to re type the letters. This is likely an issue that can be solved by adding a 1 or 2 second delay to the auto save from the last character entered.

**Comment by wbrawner** [comment]
I've also seen this, even using the software keyboard. I've got a fix for it locally but I haven't pushed it just yet. Tests seem to be passing but I'lll still want a little more time to manually test it. It should be fixed in the next release though

**Comment by wbrawner** [comment]
Ok, this should be fixed in https://github.com/wbrawner/SimpleMarkdown/commit/6473d55a7d51cfe8ba5dd3a8be5a4c6e8f8770ef, so it'll be available in the next release. If you get the next update and still see the issue, do let me know
