### ISSUE TITLE
Allow setting the file explorer view as default view on app launch

### ISSUE THREAD

**Issue by lokesh-krishna** [wbrawner/SimpleMarkdown#11]
The file explorer in the app looks good and is fast and fluid. Could it be possible to make it the default view? Maybe allow the user to set a home folder so that the app always opens to the location where the user has saved their documents. 

Add a FAB to create a new file, which would address #2 and maybe add a menu option to add a new folder. 

Going back from any file would take the user to this screen from where they can open all their existing files or use the FAB to open a new one. 

This would make this app a really powerful productivity tool, especially for users like me who manage their notes in nested folders and sync it with Syncthing, Dropbox or a similar service.

I know the app is supposed to SimpleMarkdown but this request is mostly only about reorganizing the elements that are already present or planned. Would love to hear what you think.

**Comment by wbrawner** [comment]
It should be no problem to allow you to set the file explorer as the default view. As for the folder creation and setting the default home directory, these are both items I've planned so I'll create issues for those and rename this to reflect the default screen option

**Comment by wbrawner** [comment]
This is covered by #19, so I'll go ahead and close it. You can expect it in the next release :)
