### ISSUE TITLE
Allow setting default home directory

### ISSUE THREAD

**Issue by wbrawner** [wbrawner/SimpleMarkdown#13]
Allow setting a default home directory for the file explorer, as referenced in #11

**Comment by wbrawner** [comment]
This was just merged in with #22, so I'll close it

**Comment by lokesh-krishna** [comment]
Really appreciate all that you're doing. Just wanted to know when one can expect to see these features will show up on the Play Store.

**Comment by wbrawner** [comment]
There's still a bit more testing I'd like to do before a release but I can slip these into the beta channel so you can get an early look if you'd like :)

**Comment by wbrawner** [comment]
I went ahead and rolled this out to the beta program, so if you'd like to join that, you can get the updates immediately. Otherwise, I'll probably be rolling this out to the stable branch towards the end of the month, as I need some time to write a few automated tests

**Comment by lokesh-krishna** [comment]
Checked it out! Awesome work!

**Comment by wbrawner** [comment]
Thanks :)
