### ISSUE TITLE
The Checkbox "Use SD Card" isn't Working

### ISSUE THREAD

**Issue by bytecoded** [wbrawner/SimpleMarkdown#30]
By default, the application let me choose a file from a local storage. I have my MD files on SD card, but see no possibility to read them. There is the checkbox "Use SD card", but it just opens some "Documents" folder, which is empty.

Is it a bug or I just didn't get how the application works? :)

**Comment by wbrawner** [comment]
Hey! So, the "Use SD Card" checkbox moves you into a folder specific to the app that resides on the SD card. I could see how this might be confusing though, so it might make more sense to go for the SD card's main directory. I'll see what I can do to make this a bit easier to make sense of :)

**Comment by wbrawner** [comment]
The custom file explorer has been removed so this is no longer relevant
