### ISSUE TITLE
Hidden Cache

### ISSUE THREAD

**Issue by bytecoded** [wbrawner/SimpleMarkdown#31]
I use Resillo Sync in order to keep my MD files on a SD Card updated. However, when I try to open a MD files from other application via SimpleMarkdown, I see old versions of files (without last changes). Files are really updated (I've checked it via other text editor).

Is there a sort of hidden cache for the files which has been opened once? How I can disable it?

**Comment by wbrawner** [comment]
That's strange indeed. I'll try to reproduce the issue myself, but there shouldn't be any sort of caching going on. Thanks for letting me know!

**Comment by wbrawner** [comment]
The latest version of the app no longer has direct file access, so this is no longer relevant
