### ISSUE TITLE
Crashing while opening File Save menu

### ISSUE THREAD

**Issue by kartikay-bagla** [wbrawner/SimpleMarkdown#32]
I'm using a 10.or G phone with Android 7.1.2. While attempting to save a md file, the app crashed (and took all my work away with it :'-( ). Lemme know what more details you need to solve this. I was really liking the minimalist approach and design of the app!

**Comment by wbrawner** [comment]
Hey, I'm terribly sorry about the crash and my delay in getting back to you! I'm not getting emails for issues for some reason so I'll have to look into that. 

As for the info, are you able to consistently reproduce the crash or is it more random? And do you have an SD card in your device or just the built-in storage?

**Comment by wbrawner** [comment]
Ok, that's pretty helpful info, thanks. I'll see if I can reproduce the issue and find out what's going on.

**Comment by wbrawner** [comment]
So, I'm having a tough time reproducing this issue on my devices. If I send you a development build, would you be willing to try to provoke a crash and email me the automatically attached log info?

**Comment by wbrawner** [comment]
Hey, here's a quick build for you. You won't actually have to do anything to report the crash, as I've found a better way of implementing the crash reporting automatically so if anything happens, I should see it. 

https://github.com/wbrawner/SimpleMarkdown/releases/tag/acra-testing

**Comment by kartikay-bagla** [comment]
I'm a bit busy this weekend, so I'll be using the Dev build from Monday,
I'll let you know about any future crashes. Thanks!

**Comment by wbrawner** [comment]
No worries, I appreciate the assistance with tracking down the bug. Thank you!

**Comment by kartikay-bagla** [comment]
When I try to create a new file, I get an error saying "an error occurred while saving the file". I'm using the build you sent me.

**Comment by wbrawner** [comment]
Hey, glad you're not getting the crash anymore :) I'm not seeing any bug reports in my dashboard, so I'll have to revisit the error reporting setup I implemented. Currently it'll only report issues to me if the app crashes, but if things keep moving along then it should still function. If you're unable to create any new files and save them, please let me know, otherwise I'll just make sure the next Play Store release has the error reporting for all errors and not just crashes.

**Comment by kartikay-bagla** [comment]
I can save the file, but I can't create a new file. For that I have to
restart the app.

**Comment by wbrawner** [comment]
Hey @kartikay-bagla, I scrapped together a quick release for you with improved error reporting. This should give me more details about what's going on with the errors. You can grab the APK from here: https://github.com/wbrawner/SimpleMarkdown/releases/tag/v0.4.5

**Comment by kartikay-bagla** [comment]
I successfully replicated the error in the APK you sent. Did you recieve
anything?

**Comment by wbrawner** [comment]
I did indeed! I'll have a look at this and let you know if I need any more information from you. Thanks for your help and patience with this!

**Comment by kartikay-bagla** [comment]
No problem.

**Comment by wbrawner** [comment]
Hey @kartikay-bagla, I think I've resolved the issue, but I'm not 100% certain. I see you've run into it a few more times so I'm hoping that with the latest build it's fixed. I'll post a link here shortly.

**Comment by wbrawner** [comment]
Here's the link for you: https://github.com/wbrawner/SimpleMarkdown/releases/tag/v0.4.6

**Comment by kartikay-bagla** [comment]
Yes, sometimes I forget the bug and accidentally and up creating a new
file. I'll test this build, and let you know if anything comes up. Thanks a
lot!

**Comment by wbrawner** [comment]
Great, fingers crossed it's working for you now! 🤞 
Thank you for the assistance in debugging this!

**Comment by kartikay-bagla** [comment]
It's working now! This is more of a feature request, so when I select New
File, it just saves file with the name (default is Untitled) and opens
another one, there should be an option to discard, choose the file name and
save.

**Comment by wbrawner** [comment]
Awesome! I'm glad it's working for you now :) I'll do a few more clean up tasks and publish to the Play Store this weekend then with an updated version so you should be able to continue getting updates through there.

Thanks for the feature request! I've moved it into a new issue here: https://github.com/wbrawner/SimpleMarkdown/issues/38
