### ISSUE TITLE
Allow Discarding Files on New File Creation

### ISSUE THREAD

**Issue by wbrawner** [wbrawner/SimpleMarkdown#38]
Excerpt from https://github.com/wbrawner/SimpleMarkdown/issues/32#issuecomment-418735526

> when I select New File, it just saves file with the name (default is Untitled) and opens another one, there should be an option to discard, choose the file name and save.

**Comment by kartikay-bagla** [comment]
Do you need more info on this?

**Comment by wbrawner** [comment]
No, I think this is pretty straightforward, thanks! I'll be sure to update this issue once I've got it ready :)

**Comment by kartikay-bagla** [comment]
Okay👍

**Comment by wbrawner** [comment]
This is implemented in the latest release
