### ISSUE TITLE
Issues with external  keyboards

### ISSUE THREAD

**Issue by jcarias** [wbrawner/SimpleMarkdown#40]
Hello, thank you for your fine work!

The issue is related with my external keyboard's layout. My KB is in portuguese, but in your app the layout used is the english one. This makes it hard for me to use your app to edit documents using a phisical keyboard because I'm always struggling to find the makup simbols like the star or the dash...

I don't know if it is related with android, but I only find this problem in a handfull of apps... anyway help is wellcome.

Thank you again for your time!

Best regard,

Joao Carias

**Comment by jcarias** [comment]
PBCK (Problem Between Chair and Keyboard)... Setting  the currect language in android's keyboard settigs fixes my  issue.

**Comment by wbrawner** [comment]
I was at a bit of a loss for what could have been the cause for that, so I'm glad you were able to figure it out! Do let me know if you run into any issues related to the app though :)
