### ISSUE TITLE
Allow other default root directories outside of documents

### ISSUE THREAD

**Issue by Croydon** [wbrawner/SimpleMarkdown#48]
I would like to select my Nextcloud directory as default.

So my request would be that it is possible to set any directory as the default root directory.

**Comment by wbrawner** [comment]
Hi there! Sorry I didn't reply sooner! I found a bug in the directory setting that I think should be fixed now. Are you able to change the directory now?

**Comment by Croydon** [comment]
Yes, it works now. Thanks!
