### ISSUE TITLE
Crash due to disabled permissions

### ISSUE THREAD

**Issue by joshcangit** [wbrawner/SimpleMarkdown#57]
After new update, the app will crash on save or even autosave unless permission was granted to access Storage either beforehand from in Android App Settings or tapping on `Save as...` which bring up the dialog for it.

**Comment by wbrawner** [comment]
Thanks, this should be fixed by d2604ac8ce8a1cc0466fd0dfc53ea988b576b1dc, going out in version 0.8.2
