### ISSUE TITLE
F-Droid: add to the store

### ISSUE THREAD

**Issue by machiav3lli** [wbrawner/SimpleMarkdown#64]
What about working on getting it on the F-Droid Store? It shouldn't be that hard. Only need to prepare a build-flavour without Firebase.

**Comment by wbrawner** [comment]
Hey, this is something I've had on my radar and have debated whether or not to put the effort into it. Your feedback lets me know this is something that's important to the community so I'll keep it in mind. Thanks!

**Comment by wbrawner** [comment]
I found some time to put together a build and submit the MR on GitLab: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8583
