### ISSUE TITLE
Footer obscures text marker

### ISSUE THREAD

**Issue by buskjan** [wbrawner/SimpleMarkdown#65]
It is hard to see what you are writing since the footer obscures the last line.
![Screenshot_20200517-100216](https://user-images.githubusercontent.com/4440509/82139060-8de49080-9825-11ea-90a9-3900b44b24bf.png)

**Comment by wbrawner** [comment]
Hey, I've known about this for a while now but haven't gotten around to fixing it. I just pushed out release 0.8.4 that should solve the problem though. Please let me know if you continue to see it after updating!

**Comment by joshcangit** [comment]
That release sure fixed the problem. Moving it to the top so it doesn't obscure the text at the bottom of the file anymore.
