### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [wbrawner/SimpleMarkdown#78]
Please support the Android 13 "Themed App Icons" feature:

![Screenshot_2023-04-14-11-13-44-602_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/231978363-676ad9c4-50c6-4ab7-9538-c187e7df2fc4.jpg)

**Comment by wbrawner** [comment]
This should be done already in fe2f36f, I just need to publish a release to the Play Store

**Comment by xmha97** [comment]
Thanks 🙏
