### ISSUE TITLE
Feature request: support a monospace font

### ISSUE THREAD

**Issue by ferenczy** [wbrawner/SimpleMarkdown#79]
When editing a Markdown text, it's important to display the text using a monospace font, so everything may be properly aligned as desired (e.g. underlined headers, tables, etc.). Please add the support (possibly configurable) to display the Markdown text using a monospace font.

**Comment by wbrawner** [comment]
The editor itself does use a monospace font I believe. The rendered text is regular unless you wrap it in code blocks
