### ISSUE TITLE
Feature Request: Code Block

### ISSUE THREAD

**Issue by Martinits** [wbrawner/SimpleMarkdown#80]
It seems that do not support code block........

**Comment by Martinits** [comment]
Ok I found it can distinguish the code blocks but, first, it should begin in a new line I think, and second, no syntax is ok, but maybe you can ignore the code language identifiers `bash` rather than displaying them as code.
![S30805-20523809_com wbrawner simplemarkdown](https://github.com/wbrawner/SimpleMarkdown/assets/48900241/cb40c3d6-0d9d-437d-a385-cd4263a40857)
![S30805-20524172_com wbrawner simplemarkdown](https://github.com/wbrawner/SimpleMarkdown/assets/48900241/665b3917-83d7-4bd9-925e-ef5bfa0daf73)

**Comment by wbrawner** [comment]
This should be fixed in the latest version
