### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [wbrawner/SimpleMarkdown#89]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7650665218#L869

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/ad9bc3bcdeb5540d9c523f86ff1a197367dc1104

**Comment by wbrawner** [comment]
Thanks for bringing this to my attention! I'll take a look at this later today.

**Comment by wbrawner** [comment]
This should be fixed in 1.0.2, though it may be a few more hours before my personal git server pushes the changes to GitHub
