### ISSUE TITLE
Save existing file by overwriting automatically

### ISSUE THREAD

**Issue by lokesh-krishna** [wbrawner/SimpleMarkdown#9]
Could you make the default action for saving upon selecting save from the menu to be to save the file with the same filename, overwriting it rather than the present approach of selecting save once again if the file has been open manually?

Not sure if the two approaches could coexist.

**Comment by wbrawner** [comment]
Just to make sure I understand, you mean you're looking for a quick save and then a manual save? So something like the following:

Save - quickly overwrite the open file
Save as - choose the save location and file name

**Comment by lokesh-krishna** [comment]
Yes! Sorry about explaining it poorly 🙈

**Comment by wbrawner** [comment]
No worries, I just wanted to clarify and ensure we're on the same page :)

**Comment by wbrawner** [comment]
This is sort of covered by #15, since you no longer need to actually save the file yourself anymore. From now on, the file will be autosaved whenever you leave the edit screen, so the existing "Save" option becomes the explicit "Save as..." option by default
