### ISSUE TITLE
few file managers with "open"

### ISSUE THREAD

**Issue by nutpantz** [wbrawner/SimpleMarkdown#97]
The only file managers suggested with "open" are zarchiver and downloads.
I have total commander. Ghost commander,  and other file managers installed.

**Comment by wbrawner** [comment]
I don't think there's a whole lot I can do about this. SimpleMarkdown uses the Android [Storage Access Framework (SAF)](https://developer.android.com/guide/topics/providers/document-provider), which requires apps that serve content to also use the SAF. I'd recommend reporting bugs with the other projects to see if they're interested
