### ISSUE TITLE
black amoled theme

### ISSUE THREAD

**Issue by fallsdevil** [wbrawner/SimpleMarkdown#99]
My Android is 11 and it doesn't have the color scheme, that's why I think it's interesting to add the pure black mode, on my device it has a red background and it particularly tires my eyes.

**Comment by wbrawner** [comment]
Do you have a screenshot of what the app looks like for you? I'm not sure what you mean when you say your Android "doesn't have the color scheme"

**Comment by fallsdevil** [comment]
![Screenshot_20241221-123006_Simple Markdown](https://github.com/user-attachments/assets/d144978a-683c-4c6c-91fb-78a604fba7d6)

the color scheme I'm referring to is from Android 12, I use 11 so it doesn't change and I'm using a dark wallpaper

**Comment by wbrawner** [comment]
I think I understand your request, and it should be doable. I'll look to get it included in the next release. As for the bug, if you could open a separate issue with more details on which apps are involved, that would be very helpful for me to determine the cause and potentially fix it

**Comment by wbrawner** [comment]
I've implemented this in d8f085b28f80d5ac1531bb4de712546877d54921, so you should see it in the next release

**Comment by fallsdevil** [comment]
Thank you very much for doing this, I would also like to say that the bug when editing texts from other apps has been resolved, I was going to record my screen to show it, and all the files worked (:
